spring.application.name=digital-banking-api

server.port=8080

spring.datasource.url=jdbc:h2:file:./data/banking
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

security.jwt.issuer=digital-banking-api
security.jwt.expiration-seconds=3600

security.jwt.secret=${JWT_SECRET:l2BnfXmo85R6ZIau_0or1qMJK-qKrH5yPxBPENY0-c4}

demo.user.username=${DEMO_USERNAME:demo}
demo.user.password=${DEMO_PASSWORD:Demo123!}
demo.user.role=USER
demo.user.customer-id=1