apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: digital-banking-frontend

  template:
    metadata:
      labels:
        app: digital-banking-frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/nutnoiz/digital-banking-web:b1654f0755742372bf5c2412f1ba670543cbe451
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

