apiVersion: v1
kind: Pod

metadata:
  name: storage-test-pod

spec:
  containers:
    - name: storage-test
      image: busybox:latest

      command:
        - sh
        - -c
        - "sleep 3600"

      volumeMounts:
        - name: banking-storage
          mountPath: /data

  volumes:
    - name: banking-storage
      persistentVolumeClaim:
        claimName: banking-data